### ISSUE TITLE
make_bucket failed

### ISSUE THREAD

**Issue by ad-bitmed** [scality/Zenko#143]
Getting an error when running: 
$ aws s3 --endpoint http://localhost mb s3://bucket1 --region=us-east-1

make_bucket failed: s3://bucket1 An error occurred (InvalidAccessKeyId) when calling the CreateBucket operation: The AWS access key Id you provided does not exist in our records.

Getting the same "The AWS access key Id you provided does not exist in our records." when running 
$ aws s3  --endpoint http://localhost ls

Direct AWS CLI call works: aws s3 ls 

Any help will be greatly appreciated.

**Comment by ssalaues** [comment]
@ad-bitmed 
How are you running Zenko? If you are running it on Kubernetes then the only way to be able to simply use `localhost` would require you to do a `kubectl port-forward <insert your cloudserver pod name> 8000:80` 

Otherwise you would need to use a kubernetes ingress and specify the IP address or hostname configured.
