### ISSUE TITLE
make_bucket failed aws

### ISSUE THREAD

**Issue by ikrambennasrbennasr** [scality/Zenko#476]
Hi, 

when i ran this command : 

!aws s3 mb s3://randhunt-twitch-demos/ --region us-east-2

i get this error : 

make_bucket failed: s3://randhunt-twitch-demos/ An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

Any helps please

**Comment by giacope** [comment]
Hello @ikrambennasrbennasr!

It seems that you are not pointing your `aws` command to a Zenko instance. AFAIK, the `aws-cli` needs an explicit `--endpoint-url` flag in order to not use the default endpoint since it's not possible to specify so in the config file (https://github.com/aws/aws-cli/issues/1270).

The reason you cannot create a bucket with that name is that S3 buckets names are on a global namespace and that one is already taken (https://stackoverflow.com/questions/24112647/why-are-s3-and-google-storage-bucket-names-a-global-namespace). That said, using Zenko you will be able to create a bucket with such name since it operates under a different namespace.

An example `aws` command that points to a Zenko instance might look like this one:

`aws --endpoint-url http://zenko.local s3 ls`

But it all depends on how you have decided to expose it (ingress, node port, port-forward, etc.).

Let us know if you face any other issues.

**Comment by ikrambennasrbennasr** [comment]
@giacomoguiulfo Thanks for the response, it was so helpful :+1:

**Comment by anilsakr** [comment]
Cross-check the AWS cli configuraion, I have a problem with region
