### ISSUE TITLE
Occured InvalidAccessKeyId error.

### ISSUE THREAD

**Issue by InseobKim** [scality/Zenko#56]
I deployed zenko by the quick testing swarm stack guide but I failed just simple test.
How can I solve this problem?

```
# docker service ls
ID            NAME              MODE        REPLICAS  IMAGE
ki15zc8zyu3c  zenko-testing_s3  replicated  1/1       scality/s3server:latest
z3855gemz44e  zenko-testing_lb  replicated  1/1       zenko/loadbalancer:latest

# aws s3 ls 
--> It's ok.

# aws s3 ls --endpoint-url http://127.0.0.1
An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS access key Id you provided does not exist in our records.

# docker logs zenko-testing_s3.1.j99ngt1c6vda26l8cu0pjypfi | tail -1
{"name":"S3","bytesReceived":0,"bodyLength":0,"bytesSent":232,"clientIP":"::ffff:10.0.0.3","clientPort":48122,"httpMethod":"GET","httpURL":"/","httpCode":403,"time":1519371188548,"req_id":"05872256bf4d8d8453e8","elapsed_ms":1.949567,"level":"info","message":"responded with error XML","hostname":"27db7213ccea","pid":126}
```

**Comment by LaureVergeron** [comment]
Hi @InseobKim ,

The fact that `# aws s3 ls` works suggests that when you target the official aws s3 endpoint you're authorized - meaning the credentials you use are those provided by amazon.
If you looked at the previous line of log, you'd notice you can't see your first ls - because it didn't target Zenko Cloudserver.

Did you follow the steps to set up your access key / secret key? By default we use the pair `accessKey1` / `verySecretKey1` (see https://github.com/scality/Zenko/tree/master/swarm-testing#testing for a step-by-step guide on how to set these credentials as environment variables; a more durable way to do this would be to set up a custom aws cli profile).

Let me know if that helps

**Comment by InseobKim** [comment]
Sorry, It was my fault. I executed aws cli with my own credentials instead of the defaults.
Thank you!
